### ISSUE TITLE
example files?

### ISSUE THREAD

**Issue by tomfy** [maclandrol/profileNJ#10]
Some simple examples would be very helpful to help
me get started using profileNJ,  Not sure whether errors I'm
seeing are due to problems with my input files, or with the
installation or what.

**Comment by maclandrol** [comment]
Hi @tomfy 

Installation is simple (through pip install profileNJ or just download the package and run setup.py install).

I added some example on how to run profileNJ. 

`profileNJ -s example/spec.nw -g example/gtree.nw -d example/dist.mat --sep '_'  --spos 'postfix' --seuil 101 -r best `

In this example, we are running profileNJ, with the species tree  `spec.nw` , our input tree here is binary: `gtree.nw`. We are going to use a distance matrix computed with fastdist (from fastphylo): `dist.mat`.  
Note that if you don't have a distance matrix file, distance will be guessed, using branches length on your gene tree. 
With `--seuil`, we are going to contract all branches of the gene tree with support less than 101, in other words, transform it into a polytomy (You are free to use the threshold you want, default is 95 if not specified.

Here we use `--sep` and `--spos` to specifies the gene to species mapping. If you open the gene tree file, you will see that it follows this format : "GENE_SPECIES".  So the separator here is '_' and the species is places after the gene so its position is `postfix`. More complex mapping can be attained using a gene to species mapping file (see option `--smap`)

The input trees should be in newick format and the accepted format of the distance matrix is the phylip format (xml is also accepted but you should refrain from using it). 

Since no output file was specified, this means that stdout will be used.

`
>Tree 1; dup=3 loss=10 m_cost=13
((((((((((ENSP00000433381_hsapiens,ENSP00000319590_hsapiens),ENSPTRP00000032087_ptroglodytes),ENSGGOP00000023189_ggorilla),ENSPPYP00000019224_pabelii),ENSMMUP00000015358_mmulatta),(ENSCJAP00000022926_cjacchus,ENSCJAP00000022931_cjacchus)),ENSOGAP00000017879_ogarnettii),((((ENSMUSP00000069019_mmusculus,ENSMUSP00000127393_mmusculus),ENSRNOP00000031623_rnorvegicus),ENSDORP00000008194_dordii),ENSCPOP00000020543_cporcellus)),(ENSTTRP00000004178_ttruncatus,ENSSSCP00000004345_sscrofa)),(ENSMEUP00000013647_meugenii,ENSMODP00000007770_mdomestica));

END  profileNJ on file: 'example/gtree.nw', line 1 in 1.109145 s, 
`
The output is self explanatory.

Hope this was helpfull

**Comment by tomfy** [comment]
Thanks. The examples were helpful; I was able to fix the format of my input files and get it working.

**Comment by tomfy** [comment]
One other question: what is the format of the species mapping file? Thanks.

**Comment by maclandrol** [comment]
I added some examples with commit  d31e321

Suppose, this newick represents an imaginary species tree : 

> ((Homo_sapiens, Pan_troglo), Gorilla_gorilla);

And this is your gene tree (with random branches length)

> ((Hs1:0.031, Pt1:0.011, Homo_sap2:0.021, gorilla_2:0.0543):0.241, hs41:0.0281, Pt2:0.043, gene_xxx_gorilla:0.021):0.045;

As you can see, it's impossible to use a separator to map the genes to their species. 

The species mapping file is just a tab/space separated file where, on each line,  you  set the species corresponding to each genes. The format is thus "`gene       species`" .

In the previous example, a valid mapping file will be:
```
Hs1              Homo_sapiens
Pt1              Pan_troglo
Homo_sap         Homo_sapiens  
gorilla_2        Gorilla_gorilla 
hs41             Homo_sapiens
Pt2              Pan_troglo
gene_xxx_gorilla Gorilla_gorilla
```

This however is tedious, so regexp are accepted. Just make sure that all genes are mapped. You can have multiple maps to the same species, so the regexp will not become too complex. 

An example with regexp for the previous trees is :

```
[hH]s[0-9]+     Homo_sapiens
^Homo_.*        Homo_sapiens
*[gG]orilla*    Gorilla_gorilla
^Pt[0-9]+       Pan_troglo
```
Note that any regexp that can be compiled into a regular expression object by python's [re.compile](https://docs.python.org/2/library/re.html#re.compile) is accepted, with the one exception that `*` is interpreted as the same as `.*` (as you can see in the mapping above). This was done for practicability (wildcard on linux).

**Comment by maclandrol** [comment]
I'm closing this issues.
